detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    max_calls: 3
  UtilityFunction:
    enabled: false
  FeatureEnvy:
    enabled: false
  TooManyStatements:
    enabled: true
    max_statements: 15
